const express = require('express');
const app = express();
const port = 3100; // You can change this to your desired port

const stadiums = [
    {
        id: 1,
        name: "Bryant–Denny Stadium",
        team: "Alabama Crimson Tide",
        info: "Experience the heart of college football with our exclusive fan tour of Bryant–Denny Stadium! Walk in the footsteps of legends as you explore the iconic home of the Alabama Crimson Tide. Immerse yourself in the rich history and traditions of this legendary venue, from the hallowed field to the illustrious locker rooms. Our guided tour offers behind-the-scenes access, captivating tales of triumph, and a chance to soak in the electric atmosphere that defines game day. Whether you're a die-hard fan or a casual observer, this immersive journey through Bryant–Denny Stadium promises an unforgettable encounter with the spirit of Alabama football.",
        image: "https://lh3.googleusercontent.com/pw/ABLVV86m0oIyljRCF6VpwCjTAFh-MNhSJyaHqHV-2Q263yXIwnx3X6Uvr0Y266tkKsq3J-UxOVvCLLntVwaZEeCdd--v6zr9rxYI4gGTFxjBdd3mcao2BlHENq5KA-IuHTmre6GraiG6AVdLI1RhYfePYTcbBmwTuAPNpwj57pbmb-WUuXjsaCb1mvHUV4iPMesDlXEUANbtoRZnuV1ZTaNFfPY6geZr83fYHKRHY-1kVmD2D5C4I0EEzI4Zozuer75rIhXC5nAVXy5TZsWB5bveaQZn9JHYvCb5aHfOKp2oByS8vnB0IPS-Oy5Y2VWQhPFEyyQKe5la8np0sjMjTG1OBVCw0jDDLBnuVzPAQfMeLeLxtKpBtQtQnVUlRpmQzxtfMAh0qsLdVNuNH3fU14JRXfMAhA-8jnEBp5drHZJ9q-053TqFldrccCQjpURxNl_DKWzuP6y7dvfXfsI7Nq_szMCPb_ZWPJE3UUgwID33hU0qaDac3zqeOtNFOub_kxr9x1NfMaSrXN612YELpV4lIfW6wu2MEcmVhyupwzWkIGAub23drhfdm1j0lDxmiRc1putTATwH_Zh__OpkD-kPVtiJd8GH4cO337No6E77kfP32cmlW1uBZd0VabD0-S0ncIVoY-SadcYK9bBXJSr1tCx12RRnFCpIji_kXlNpGY7g935FLLkiFt9rsfs2FyptRL3qvgxAGfPtY_RapNWqPJg0m9npMnRJVXsGgXZbNNEbuaPyZPb0pu0-nMHd9mwoRQWt0cz_9KTEnLgeTz1igIaGnBy0w2HkfHR2KcTM3uG2Te_OwG25fdPt5KC9z-K70rBKY04ZZMUpWi7XGQgBsGPtBs7vOA5g-_k37EH3Au4qmICgFs7SubI2vCi4j9f7SA=w1024-h576-s-no?authuser=0",
        price: 25
    },
    {
        id: 2,
        name: "Donald W. Reynolds Razorback Stadium",
        team: "Arkansas Razorbacks",
        info: "Embark on a thrilling journey through the heart of Razorback Nation with our fan tour of Donald W. Reynolds Razorback Stadium! This immersive experience invites you to discover the epicenter of Arkansas football, from the roar of the crowd to the players' sacred turf. Dive into the storied history, explore exclusive behind-the-scenes areas, and relive iconic moments that have defined the Razorbacks' legacy. Led by passionate guides, this tour offers a unique blend of excitement and insight, making it a must for fans of all ages. Join us for a captivating adventure through the pride and tradition of Razorback football!",
        image: "https://lh3.googleusercontent.com/pw/ABLVV87KXf1z29p8_r_9TpOIM9Ai_C-5BwPn1bQOE8IqSauguPJ8q8lV901pDj2y1tpQj12M5ZXWcXMdOb1ysVT__gxASaSU1A_skEEd67rXRMEcOp7FxjjxYZiQ5w1Cn9mGTIdZ0NhVt-hwTkekhlQNStQquMWUZcnAeoiJ3M7dOjG1DmMEZ-itB-M7A-hheuX2gt-Rcx2IqXfZtdB3ZqOfbcZVb7aldF8Ly-8RhUa1auFNcMKqXNOqLaLLiV3rDeC_OKJk_7XwrLEDtfOvAgihBF2zggET02vOi9BoupMf9aGz_D8kf3gze1FHu8Davay4-XD34H-qCN_Z79sQver1X1ebmot-r4wgUZPVzeJb1L3Sj3qrjaNSJ8m9s-tcYSsaNZQYlZ_3_fekZwOs-WjjYmzSYPuCOFqwAd5DJxRxpC8gwfYc6DId_ZK3j4fJVLQp0UYBMkVvV0EK383mxdlpxym3xyAGuRRHzDwJntuqigkSCPxIJKrGp92-AoJAQVZ1kl546gOfoQA1v6fs5IgkqwPYxvDllCqfG026BylMrvk7jMgc1Ey52saVquSmfxrW36lED2Xz1wPm667vM7mB0GH6OdJYZXtIrIhvrJOIRUbRyIB4vv1xDjxScT6q-6Opv7exZLBwlXddDLnKus8GHsOR9DH13F6w-iWTGTiJmRzv2M8gnq0JLTLofGTzIgpWgWU_vgqPdWYu0Y9P1n6tLqk6QPPKw46tvLBD2SVoELUyeptVXZZaRgJBhXZNnDdQ5xdVlc6Qv4Zh6_cHpkYnwCEfKF8X3hOawSZuyZyn1nvID3J7IQjFNJqO3tIp_L8HBpc3A6kLLw3X_rTlukDtOexn5TMt4ixJbKKVQ5wrUIU57lxN6G8tSsXYDuG0n0V7dw=w1024-h576-s-no?authuser=0",
        price: 20
    },
    {
        id: 3,
        name: "Jordan-Hare Stadium",
        team: "Auburn Tigers",
        info: "Embark on a legendary fan tour of Jordan-Hare Stadium, where Auburn Tigers' spirit comes alive! Step into the heart of SEC football and immerse yourself in the hallowed grounds that echo with tales of triumph. Our guided tour offers an exclusive peek behind the scenes, from the iconic playing field to the revered locker rooms. Be captivated by the rich history, traditions, and the electric energy that defines game day at Jordan-Hare. Whether you bleed orange and blue or simply love the game, this unforgettable journey promises an insider's view of the passion and pride that make Auburn football truly exceptional.",
        image: "https://lh3.googleusercontent.com/pw/ABLVV84GAM45jogk8UuLv8f-Pl4zPbZhzovSL1Yrd0esvXkXLqX01GUvVeoNwe3kfP2vZGqf6Jvfae_diG3FtwlRip_arcB7JKwl9UZC6da4jkhBUL_Wcz1HNNq_mKe1XGhHxfsvQUFkNjQipCHKJinnZyO6SmIWLtf5lYfhzt5zemE9nI4y4GabEfTUPBQRL3Q6kDgNuh79DkPqgb3MK6-IMHZBR51QCbG4zHcBE_kTOXx7VjgmAdZ6PdS5IAAnLRIYqA7je4kXyAZLSU9vxpZW6_r12RAx1AEdaYIUVF7KC5dmo8Oeju0jPsRFvmYwU6lpXERFgG2MslMb5BbzHioypVQsFMv8UQVLvQ2mAMLe0bMmuJmZuxmqAPalnLZjOPyaAIyn26c1Yed7up3dMwR6VUZN8JRdTuUX_gQG85D0Onb-fTTDQpXmGjpxHTIpEgVfCRhljSIOAD7sYTNZpJrtPrgvaQYu75cYQF2TsBTmHnOmVrAar0pfgjEixT6pCFZ_ZjVnbYmJGf2o2VjI4S8mqI02r8JcE77P9UwhB22hsVjg_1LZkjkc4yUoVS4BdjnogfvNI3-Qlh64qwfO1D0RMdERlKLaZnf4I-HabS8gDoVN6TLU1rhPpHavGu86fSLDsKaj3n5yLM1_kyaf3duI0UNu_jZ_WHvJHCoH7ZvhQN3tyJaHpcPJyBJgu65m6pQ3TZ-WsGugx4vCbZkiA3JnzYkNIxzgogeW9k0FNNArOKpdVMZwvb8qDCJur0hCyWPDNT5roZPlqDnWJs1YDis1llMNmYDsGjVgRTCLYsGw6yw2a1AbR1QCP23YQPSLC5gX50shhJOX8KSAN9riXLp8_EGgUuJ6LL4QE3p9sxjnnj4CEQqDlFxCzIKNMhI8Jy8a-Q=w1024-h576-s-no?authuser=0",
        price: 22
    },
    {
        id: 4,
        name: "Ben Hill Griffin Stadium",
        team: "Florida Gators",
        info: "Take an unforgettable journey through the heart of Gator Nation with our exclusive fan tour of Ben Hill Griffin Stadium! Home to the Florida Gators, this iconic venue invites you to walk in the footsteps of legends. Our guided tour provides an insider's perspective, from the storied field to the legendary locker rooms. Immerse yourself in the rich history, relive thrilling moments, and bask in the electric atmosphere that defines game day at The Swamp. Led by passionate guides, this immersive experience is a must for die-hard fans, offering a rare glimpse into the pride and traditions that make Gator football legendary.",
        image: "https://lh3.googleusercontent.com/pw/ABLVV84GvZFCrXPew7zo9IG4bboBYYnsZPkEZV6dqpg683-8bdsevzXxWtIpFQ4NFLr2PgvPY6JeUCUCq7mUM8tPmNptVi0TdvxhtBcND8hAEZGDWGD9Qql28SojRrTcLMCG7wpDEnG1ro-0Zwbdwva1bTgqzpwT5CCNtomiAZEF3hDexyqRiRzarzKAV2EHFjSZXWGgR8jczgMBgcuhmKZlYTN52AWI1b5szyaGUv1p1y7AL6rvsygGIEC1ZCZIz6mHrkrQDT49F5u8g-Bw1wtB5jR9wyqH2GmDSJAbgyRfEIIjjo9rcKlXPvAAxko6Sze3oX9-AC1V1uuJ9ZWB9KtlXkX8D84pjU3bi1Qx4qlyGcV9BRDUek9pb1Ncb2XN47tfnUrNi6qWt8zCnlTDuGNKSMOkXu7gSdvr8CLu16o6wEpvXgj1Ab3jhRrsXy0kdo2y9YtyZq3_ucyydc7G0vO7B9Nt28tK0-SvMxPyyJwb1fMN4_QK-kyXoNPm79yGw8z9S-7ohLLTgRhcyUSQEMAIefoC4uWlyXL1o2oQPqyt6gSj9T-U8KVYCRMLZmITjgiEpIcywOqj3cOncOFN3QwH2W_L6RpMH8ZhOLceU1dkXjUz0C8OPR_8xH1KbD84KyN3x22IDE4tO3Xi46cRRqZEv8t-UyRXtiAs7QcWv_j4Qz5Ctnqbj978PDBNpPA7x80UQHdILlyhr9rS1SXIeXiDXTS21kfw4WcBisLA_riarJfnW_9Tkg0QvuSME-8xCz-r9FKSFAAaXecX7VqsrsSVJ5g_9Yglxnip2Xv1ubKLgghorYgYyVyM_JFQUAEBtA8nGZQl9C898lQzUBVkIyZFOINZeUZBK_D2-es3dqCVNu-y6jpZ9fD0ReyRdk-TqqOgVg=w1024-h576-s-no?authuser=0",
        price: 25
    },
    {
        id: 5,
        name: "Sanford Stadium",
        team: "Georgia Bulldogs",
        info: "Step into the heart of Bulldog Nation with our dynamic fan tour of Georgia's Dooley Field at Sanford Stadium! Immerse yourself in the legendary realm of Georgia football, where the roar of the crowd meets the thrill of victory. Led by enthusiastic guides, explore the iconic field and hidden corners of the stadium, gaining exclusive insights into the Bulldogs' rich history. Relive unforgettable moments, from historic wins to time-honored traditions, and soak in the electric atmosphere that defines Sanford Stadium on game day. Whether you're a die-hard Dawg or a football enthusiast, this tour promises an extraordinary dive into Georgia's gridiron glory.",
        image: "https://lh3.googleusercontent.com/pw/ABLVV86ZqNks-Py012_LGFyaYoMRmtjTs1wnMUIh2_zr0QEt9COZSnih0pR6RGgC_Kn-K2hzqdafkyQL1s3k_r3tSJGJJ9JeCtEvZcqOpKRLVaaH1vs6uqmwotr7MLmZslqj3toMJiF1YnfJwcoIBTfLlsOEjhHuXPv2wdU3JM9Z39udxMmAnjjAYSyzx0EH_xlIUfuGIVoXDYeIPmUxGu05Y6JfERHyNxsKBec9G3da3mVkZpkTpZry07k-qIit7INm8GTFLHpW2whEPLWBMFcGEmqV3xg06BMb15d6Pb681VL42k7m_ih1x8NAUYwu5x47CM_LTDmne5vcIlWQ97n_0xD0dsnhBVU61Y3X8i-afNcBZSQA0cEDFnpiaLRaIWjT0PJi2ZKck5cwJ7oGawBF62Pooh4xxudPwYjU8-lwoIpoJ08PnfDPdcDtvvxmveSLHgJY7vyYynStCrEHiMOY2Zkh0GOk3Hlq3UAsqngsgw_HqoXl0W_WwfmRbzhkLvZw-VsphpG6MG7ioOHM3uU9ORm_PDE91FxzRNkDYXPb9dMl01VjNqStSA7y4_wWyTD6dTMJR5B_yli-J70Vbvy0d8YNmxfhOYXUtlTRJDdaqGZjG9A5tZfXUWmbMkhvinsSn-m8rbTQE4cONjz5uVTs8JaaNwNHpEfm-LurHgM9ntyGhiakjXZK4TIIK16_NA0zb0Df4bstIF-HGlaq1pMuy21CyRqT-CIyDpTMvzZJffgsDRXl0TcXqNLcPDq38saj7xvHQJxM6e4obMyJEof-3YZKquDXB0jQDZ_9HoSmpcy4zUjF-pP1JM3DbEzyKdnOroYNMjr0pGiAVyCirmMBiNmHmvCGVA-rNUqqCIieB98m6aBmFA5INCCBPOiVlY406g=w1024-h576-s-no?authuser=0",
        price: 25
    },
    {
        id: 6,
        name: "Kroger Field",
        team: "kentucky Wildcats",
        info: "Immerse yourself in the thrilling legacy of Kentucky football with our fan tour of Kroger Field! This exhilarating journey invites you to traverse the hallowed grounds where Wildcats history unfolds. Led by passionate guides, explore the iconic field, delve into exclusive behind-the-scenes areas, and soak in the electric atmosphere that defines game day in Lexington. From the storied traditions to the heart-pounding moments, this tour offers a front-row seat to the Wildcats' gridiron prowess. Whether you bleed blue and white or simply crave the excitement of college football, experience the pride and passion that make Kroger Field a haven for Wildcats enthusiasts.",
        image: "https://lh3.googleusercontent.com/pw/ABLVV87MlUYRCe6phnriyck5rIHwwOtNaLAwuMEQCBrFZN51GhlZCO01Lq6K9TRedn21p98RY8ao8BYszaLh0emRUcP7ybuksvgS9yPf3jntg4EwU4BuY2R6kszhQ04N-6_Jj7ABRXosrVjSnkaQhjNlpsMj2ftzvjjNac-NRYRZY3c4LTeYNItVfp-EQaPESEZj_Di5GvnckwXILuDNXFRPPbAmZdnw8DFuwPIQyAPDKE5TdbA2mHhcihaLdzw-LV2Ih7C0tptlFJ6GNV3-BN7abLPS3k1rU1-9qUALIdc-yvctT_DDIcer3SLaqsxASRDiKAnIgDAswMMJCHi_O5C6cifDyCbkM76kVvjkyz_OcZhUDSOoYvi4b3wvMa3t9WFvMvy8SgSlXROd5-iSdKkm0B0ce733FA86sweFrnHFoYK1eIlUeiNclnih7lOc7-lVEjnoUdX4byJLk9V-pjSrwX49GDN9VjIfUgJiO3uHBfr_Fo7uET_phlv4-M7mdrzFZWl8q97WQ2rDrzBh7zeNCxiDJsUWKYEdJYhV5pfazzF94LTT_7pTQH81x8CfsAfgUClOWUIJ-tUADrHatwuF71XPVUNM_feLKXWoap0J6ABNUCMgCGZEe4ZbJR6uiKDmbwKrKJEIuZxNMrP7QHFQVlHIfXZl_UdQ6KoWzGRyKqWXbqDuIGN7SXnyVx7xrD5l0d2O_vmNT77dp7r3PdbADswbng5LX19g3VX2izrWCccODFB0iN_TEZGUxil0r4K6bu9iDNVLWAa8aiQyxkP57FQeGdgjMaIofmfCyo_j1B7ROTT9-59E4IblH2shRipBplW2he3l32H-x7-kXeYeExqO5fbjOp1Qvpsda0XjZPUSavsYAO4iTIfpng4xfV_8LA=w1024-h576-s-no?authuser=0",
        price: 20
    },
    {
        id: 7,
        name: "Tiger Stadium",
        team: "LSU Tigers",
        info: "Uncover the vibrant tapestry of LSU football with our exclusive fan tour of Tiger Stadium! Dive into the heart of Baton Rouge's gridiron passion, guided by enthusiastic narrators. Wander the iconic field, discover hidden corners, and relive the monumental moments that echo through Tigers history. From legendary locker rooms to the thunderous stands, this tour unveils the intricate details of the Tiger Stadium experience. Whether you bleed purple and gold or seek the pulse of college football excitement, join us for an unforgettable odyssey through the legacy and fervor that define LSU football. Geaux Tigers!",
        image: "https://lh3.googleusercontent.com/pw/ABLVV85np8ovD3nbCX-GCLghUoDnXS5uMDtINKH244iBFTk-f6Hen5I05--g5o1QyEMSRQwsnd0gdvXmGu7ML_dsD2WKj52o2IewoiE1hRuW7bju54T0ZYsz8KFO6toBrqHQJHBvT-CjjQ8IFjJnrNsbhWfl6INKEsBwAN42ny8K9jxfUCDg-tg3YnNUzU2sdxpGr7B4WselixRG-dUqx49mc-Q34KONQ82CRp6toqfqrgZXPsfw87pXwbWMlj2YiX48AapTx5frf6iPO9jF4Wi785mnaJlNLxiLGtJpc4ZFAvbliQGMqUN_M4IfW4x5thaH5kNbq9heCqGaOhJcey_p7mofgWcIQ8AGMKmLeA7pASpXXS2OivGn5V4K0yeVtVH2jMGnnpWPLs54A4MsNkHndzhGJcZV6Vmweqtg4poqt7M7Zdr-PoWNWjkdEjXD_OD1ep__FwONqPEMbZx3b20wxIxIPlZj8AkDQsYNpc6kRWfmrfd2jPRIHtLlaqVciBgSr03WuQxpLpIhBALq7D_G41HNQCCXHbr_vFWnRcNqE46x1sMG_KZKyYsmz2CeijFwrgjGIVRaeeE_bmzaIJxUuQU97YRNFhIRl3sAypm0KEeMtVfVHwpWL30Q_a53KZ2ZtAfoFyW8dmCqqbb-5jE472xNj_aUADmd6boHsjUa_Pok4OY_dDi-WvfdTyqa_DFNmX6T8EHahmHIMln_ZYL8TDzCLS-gd8-FripGrfb1Wxc63W22Mwd9o3PN6sRTJGjxTBYciTqSdxhh3ViBWsOV15xFREiceZmvF9dwzcEqn449b-ptYy0fPZsu7mJ5gFQGfcNeYjL5OUWsgDb9ZPCvXdmcRXsxuvgQ8UT4lX16-0ylAqGECpEuIvDZMW-uOJezbQ=w1024-h576-s-no?authuser=0",
        price: 25
    },
    {
        id: 8,
        name: "Vaught–Hemingway Stadium",
        team: "Ole Miss Rebels",
        info: "Delve into the heart of Ole Miss football with our dynamic fan tour of Vaught–Hemingway Stadium! Explore the rich history of Rebels football guided by passionate narrators. Roam the iconic field, discover hidden gems, and relive the historic moments woven into the fabric of Oxford. From revered locker rooms to the spirited stands, this tour unveils the intricate details of the Vaught–Hemingway Stadium experience. Whether you bleed red and blue or crave the intensity of college football, join us for an extraordinary journey through the pride and passion that defines Ole Miss football. Hotty Toddy!",
        image: "https://lh3.googleusercontent.com/pw/ABLVV850bdD_CcD2jHhhlymcK0TZP8ySZ6Tehm8hJExlYPDVrmxTOO2RGlR02stXHpwLD8vwZQO-HLbI5dLsTwYoYBYgrupH7JGE7wKVnRwH0gGYU-v9K59H2wxR4A__d33mQjuv0hYfxPVgsrNA_LIy7ke4K_0azWH7swDeav-fequ_L7bOKSS7Gstp7p9LL9h0HXNpBuW9b_eeYoW7-wgIzMZTYmJeAfAz2MJ8mn7Huyhs2rMJjtF_zq4RZNGKhElIoLDi7mP2fiJFcuMIMB-EoHlEzDYHGL-__sZeO_SAhwhFR83fNPaJLG1MV2HQ3lwjtB3kzuIHH2y3SPx6VxoLOJDCOe98kpEfFqLpyHp0iimmNj98Reu-fKsPDoGwWHVHKlAc08ABLY6UPKSMHuyMwM8Jfx1CZ84QQ96P41axT2WX1kJ53lK-ZC6-TftPTo-AG8cTQQHQHYdszdKduajfINcnC_iPfQeMRuaaQIBjxnJBif97UwBl7JnrXPjlMXa87nTt6LXErY7tj3dRdpERxGuy6R3d8bNgNqSB5LuzoMD52qw_nBkOqoalcTvy0D4HrkvlTIEkkqCPpaIFXOLI_7y4RGBYRKFvD-h-6G2veLGbgzhdertP1qMBtRt6JkVR9l88rjiE5W6F-dBqF_tUeJalheRgeqXXOPpXW6gAQ8FuAmsvr6ZBsWJbQ5NIcXl6YniuoXycmpadCGTmUbfBRIOJxrAX0_9eMiUKzcYkVrX8ZqJiy1wyKqEcKML_nf16AGwXwZsaDuner_gF03XdByUJozD1XsF9FsTanyo7TTxf7uiGsdYc0NV2GqzKmPqPn-SozU2s-h9xNOigkyrwGii0_i8n0d-C7Ch633mx8b59FtgYOZ8-gEDIhclsBQYq3Q=w1024-h576-s-no?authuser=0",
        price: 20
    },
    {
        id: 9,
        name: "Davis Wade Stadium",
        team: "Mississippi State Bulldogs",
        info: "Unearth the pulsating spirit of Mississippi State football with our dynamic fan tour of Davis Wade Stadium! Journey through the gridiron legacy guided by passionate narrators. Roam the iconic field, uncover hidden gems, and relive historic moments etched into the fabric of Starkville. From the revered locker rooms to the roaring stands, this tour unravels the captivating details of the Davis Wade Stadium experience. Whether you bleed maroon and white or crave the adrenaline of college football, join us for an extraordinary expedition through the pride and fervor that defines Mississippi State football. Hail State!",
        image: "https://lh3.googleusercontent.com/pw/ABLVV87myz0gZOHUEKMkeCsL95eDh9jBs-Nu-Qb1VpJ_wEQ0UWF4L49hUAk_mMhhLJMSwoEskKpIlfkTtzRAqbieg2qzPAcaE15c86lbPK9SLq3S0FFVuhC2z66A68XHhmB7QldvJ8chaNQE2NYydfPSr6WSx4wXddc_n-qaJeKSYxmNkjTQ9oaN3USOIs1Jc1POG5dzevf-DBBGKIp7OEKCqhmKSy1GODPmYhaqyAUOgxMAa6es5mE8HIlfF6tnt2BamWxinjnIsf__3S1fK_G5IDIuqYUvzLVndKNX_4AgtyTFb_9FpVBIWD3bSssDXGIT0c5MKUQBxouhRa_ZGU4qnZEwtQTvEg3HFVizzVs9amjElbAuIvITrlshTWFOc5C_9RN0QCQBlPc3xBhNerDg7P9twyxNyHRvmkBwO3IzpZcNm07r6noeLsxgWJ7riBnYDMVthskQYytg4T0nb2Y1CKEe7tXm1VogV6lri7bJnmjl8phRZpF5y9nfvyXpVg2f7C1-R2XDOYAqUHlSwMv017LFoT7QxbIVMX8K0XkUmlrX-UCOT4n25ohmBTZ9Ex8j3HyGFm2vEiW22WZfkS_xgTeBbSnIrJtGRjlZj2OOLHXwpe4zAGd4o2lEQUKnm71VRGOkdFZCxge9VP8X0CBm6N5BVO78md8fOcWMlDFjo8wwPY8lHRy0UFwUSufILYH0XkrR3HpBAK0ePsx79R3yKFaQGrd9H1pauXpy3pByAtyb2-cXnL9mjml52CNfJrSyP1CVJY7mOVArg2CbbXKm-oXpsM7BhZE331TNA5Mu_ubUuL-6BZt2AyEg0vXfmDArsGZG1Qx5lniAB-mhHnaBB72_42jlO4V1-JhRFtJR4Cw7f_jk_peIHflfWbqkp0k_ZA=w1024-h576-s-no?authuser=0",
        price: 20
    },
    {
        id: 10,
        name: "Memorial Stadium",
        team: "Missouri Tigers",
        info: "Discover the vibrant history of Mizzou football with our captivating fan tour of Memorial Stadium! With passionate narrators as your guides, explore the iconic field, uncovering hidden tales within the heart of Columbia. From legendary locker rooms to spirited stands, this tour unveils the exhilarating details of the Memorial Stadium experience. Whether you bleed black and gold or simply crave the excitement of college football, come join us for an extraordinary journey through the pride and passion that define Mizzou football. Go Tigers!",
        image: "https://lh3.googleusercontent.com/pw/ABLVV879My5FpUmXxv2mMWvLV4OAEtXZbXG0uTc946G8YrSNoJhMasMSCApm6XcT9WGDCwHv4HDXjgFH2hNP_Uow8yzu8qKe3IXq9pHKmVX_mWfNQiKiFnNzPPE2MRd2giauvZr9coIgsq-qLzX2YTXRJVMoIa-k89For3IJNObQ2P7dWKXDzJ462I74GHvxc8rlXwA4AAud2o1Pv4AIlKv_XYrlX_3e9pEA9B2qm3wcB8PSbJ2lL7I-LUatx5W3_hAqawEqeFclXiahSuDq34xBxhzVM7HMKU7XgvxdXQvSkWYkVEpV1ozRh9wxDFjdylQvcoMMtHmA4qZvD5N7f8bF4vDRdydtRKUIS3WtyeoAcjfycg8laiRzerioOe38F5z4choMdPIj-qN35c7Nz61Ubywj_bdpi6hgFDL_fYpEiic7Ld6Ka7weijwFnuCnBGS1qeytYTGavM6qMaj--L7up4FvkbjaMPDg6RbX3sd35MYo6rjptoLrYUJxcSDsGbHL7JS88Ofl2nJkV17fTvq9v9wd6nVPMKn1DBcJVHn_jdP_Vg8kA2jqUxrMkhwNsr5pWcU-ogKCjgYnxNSoEg3r6yTYv0Ioqu6uMDpRc6iys2D0xlb4wR9Fz-9UT56kg6PMUhutq7NMPDwiYgFmOtcyHJxYjBvNzHDW7zHFXAVuolYBS9K7oraR1h6SAxOH1zcxLuGJxq1x3DVaAXq8tFH0wkVmxSikHUwYn1zIkIlaKSDTvwredJ0gI4Uk4hwAn6817ADWDdtZ1Vi8deAY_3SwtvKCqm8EP_NrKzUzLhWejMzEmbPGtmiTtR9jFEux5yCsWw2JeS0LUqsL4plzZJLqj8XeB1VhjPqPxExtWMkrEvwJWhpTnzQayjIm-DN0PtUd6w=w1024-h576-s-no?authuser=0",
        price: 20
    },
    {
        id: 11,
        name: "Owen Field",
        team: "Oklahoma Sooners",
        info: "Get ready to be swept up in the thunderous roar of the crimson and cream at Owen Field in Oklahoma! Feel the electric energy as you traverse the historic turf where legends were born. Picture yourself surrounded by the iconic sea of fervent fans, the stadium echoing with the chants of the Sooner faithful. Explore the hallowed grounds that have witnessed epic gridiron battles, and relive the triumphs etched into the very fabric of college football lore. From the iconic stands to the vibrant atmosphere, this fan tour is your ticket to bask in the spirited glory of Oklahoma's football fortress, where every cheer is a testament to a rich sporting legacy.",
        image: "https://lh3.googleusercontent.com/pw/ABLVV85e_a52fZ8mGr2ZK19_uI4ougUu6swXy8CLB6Qs3vMrW47ogIQq9ip__lyczGwMFshAUtTF3cos7FwJixcfDj2qi14UKb5vS0t2KXkecfl_7GBl4yyNnTLcT291bmbwBndAmU7p096wjhX9oVlWEAkc1uJyxPuJXBUj28j3XyVtFJ-cKrVwb9l10peHuQBOAkS7mNdTLIN_cB494Fl_r8afCwfj_OmZBHdlspx8KlsVkkCjgTMRHtVjNFYomQJRtl_bVe1dRkXRZ8bG44Cq2d8vHzBN2_S13Vx5ELT27p4KttRO7aNiRimHN2p9LXKv9jkHxF3vPBjvl-Zz_0eGNc16DRoMAEfnILfAk0XFB8u6xI2eFqBpfGI7sag1NvB2nImU1IsRMkGJc_0ZtmCK_3lRSJVs5o8rIk_Wcn0rVliXruM6VBVdY1_Dr8MWA-KAETLoL3K2sA_cMlyXt8_uQjJLXpIfgM8hra7iVTlJIO-X6d_hbZDkXRVC89ZrBHu8gNJcy07bfQiLqUmdbz6vYA1HzH8b8jo-ZPOo-O0ZkvksbRWkGFwSGMpikAyCnpEqK-hk3wmxejIvmo2YWcrnGRY4-aTgxK4ACDsgpNgnWKuvRHside7pos9jcS40k5DL_OQ18Y1pQQBix8IsZnz66uucg7M82Khok7CSjiOThOI3P1BU-KQEE7KwWTIKEbjmpSdPu_4DA_UYs0gZKizVZZzqKrvzVo8wcpwzJSemSBEHYxRMTQPkZ-Ok1tdBnTdZk4SSNSpunzBds0qIXsr0O0FKP7I0maGd17mh0I8rUhOSonJL4D6tJH87q5arNICyBt19sGEU6ZbsK96-Errfm6kn6x0egBLdq3P9KJfpBb6NcLLr1xhlWrHDMuzS6F-xQQ=w1024-h576-s-no?authuser=0",
        price: 25
    },
    {
        id: 12,
        name: "Williams-Brice Stadium",
        team: "South Carolina Gamecocks",
        info: "Prepare for an adrenaline-fueled journey through the heart of Gamecock Nation at Williams-Brice Stadium! Nestled in the beating heart of Columbia, this iconic arena pulses with the fiery passion of South Carolina fans. Witness the sea of garnet and black, a living tapestry of unwavering loyalty. As you traverse the storied grounds, envision the gridiron battles that have unfolded beneath the southern sun. From the towering stands to the spirited camaraderie, this fan tour promises an electrifying experience. Feel the echoes of triumph and the roar of the crowd in every corner of this legendary stadium, a shrine to the indomitable spirit of college football.",
        image: "https://lh3.googleusercontent.com/pw/ABLVV84Ez8-rqUQ3HBnaeyDX8a5gOAgJ2FGriCzBScxu4SksdJ_j8tjU6O8EKU8MkrybZ6UbWPgi4LjBQkDI58cuUVN7QNLx2D4_0onJG2ykuW143BQxLo1vNz6hfo-60tv4B2PWIzLKPatfkCqxa6r9WmLNQs14B9VWB_iCIWYuy7HwbgQqEsCJDtJ3Skt-Mopc_vIRm-eEUeRMQ7GVfXVAUSXSk-OQY3DUMzpAEebNy8Wib5yT4gBedGACo9LenebG4aVN7QSefAUDvPMEEP2ZaD2ArF8lgdzUWJxlHIt2g0uIrqmIyZ6bjNspfCW0HYWYdFp1j4FgDr0z-IpidQ5MVcklCfjQLIbyq8jUQ1fLKyUZ3yfO29zdQz9oqL1fd8a8VPlbxLSoBysrjWCf-tCcJW3HF-ABwgblyJQmjdRKgDOYQxT6KOO7kAYi--PucotJ4c9Xh4rLc44l3zXR8LDHIFoiHExDggwIQtE64f0R9BrBB0E-MnwpeAfuuicjSguzSdZ-QqQuUjNfCpMkbcsdVd6gPd8wb5KN-zDT-q8EnlS76NyPwsEyK7qfoyA0IxoHrOCZPWO4cXbO-f-BZZaSdyElS4xfszeqIIVD8zZeDvnhm5FzWSRjKbyxt3a3X-0CmHjn99h9TLNSXXCRrwlfE9_P4AzedLqhducvGlGvZ5ClLFA7aMkKV5RoxLw-Cd7FlSw1-NPv7HfdJt_jRCy1KFzlWyMpdq629tKpSblWs4Zm6bkcHcjt_C2eBlzuD7manpLFxUSLWefmnh1P7B35viyT1CzauvAeeuGjIqkDMJm7JNt40I5DmOigxAPOCMx7lyt6QG7Z45u1R0_TQUFcH4lPPIsILaf9haDP3wsy3Xge0JP5l9Zx5VrGK-wlWrpd8g=w1024-h576-s-no?authuser=0",
        price: 20
    },
    {
        id: 13,
        name: "Neyland Stadium",
        team: "Tennessee Volunteers",
        info: "Experience the exhilarating vibe of Neyland Stadium as you soak in the dynamic energy of Volunteer Country! Join this captivating tour through the heart of Tennessee football, where the vivid orange passion ignites. Surrounded by enthusiastic fans, imagine the resounding history within the massive stands. From the distinctive checkerboard end zones to the legendary field, Neyland Stadium stands as a vibrant tribute to the deep-rooted traditions of the Volunteers. Dive into the pulsating atmosphere that encapsulates the true essence of college football in Knoxville. This is more than a tour – it's a heart-pounding expedition celebrating the indomitable spirit of the Volunteers.",
        image: "https://lh3.googleusercontent.com/pw/ABLVV87vCMoITtnifu-9rO-WYNlAUTOmaB2mrA2re2PHalkExnEAbIyElveMYngLqoVfhlJ7TdN7lqeGsb3I6afHYU-Lu9mvBELaXz03ecKdR6ez5eJtWDBB4levzI1PHVSqzQqFPRaiDm4tkuyvUlUN07r0SgY9vopvXz_XGk1GpbAGN5Kx2BTwt1r-IvPo3xoab2KnvRh4GHGA6K-lMkfZOOkR1GiBVqBBXdQxlxyER9HLRhID9t35CHAlYb2iAcYJqF_SsvuNgSTGbLnWAcx7hDCoF0Xrz_PZnLbFRrTMdZpUUZWGFZsMYznG2zL3VKjzIAY3_IknP931zVDej9p_Zp-ZWsQGlstY5uSaZxtWESEWTc70pNzA0JHG-1st36MWZZQzHBiNYkfxgXEVwZErnOSIPIpxHaNMA3Key0bMuA4rOaG65EJ3JWYJESwXyVQ1MaybmxWS4JV_RoJTXdAVE-pk5B62EZ8OUpakNK91Johtt3Y6tl4I3CcgCduM-62nP_mUDZaYd_VYEGNY_MilJU_ObVwh7oRRNLeKMQiBm_oI-G2VZ_VpcJ-HuiPfsxVdzUjsF8vqHKY5SBic3O7tX59e0oIRUPdEfROIuvpKb5YkrFzxmWXahi_FV2b2SIeLn40I0QYBZJhMyk6xzIMbDqZ_r6FcJXvmhS2ncU99QBHssMEruq9leHPyvMBTK5I1haAGF9iJLPSfu7DWdLHtdmulHX58qyUKd_V3eSlCpx_cu0aoN0yka2d_dFvUGuWOraX766DfkQ2lv38nxNr0nxvFzf_C5TRs2-LifnXVXrXsNdo_zvCmtf67hyO7tN1prlL_P2Ce5Db1lMz4Dje5CArVWuRPRezA9ofPE6YsCEbvhqhaVzWEr4GOgroE8_63zA=w1024-h576-s-no?authuser=0",
        price: 25
    },
    {
        id: 14,
        name: "Texas Memorial Stadium",
        team: "Texas Longhorns",
        info: "Prepare to be enchanted by the magnetic allure of Darrell K Royal Memorial Stadium! This tour offers an exhilarating expedition through the beating heart of Texas Longhorns football. Sense the infectious energy as you explore the hallowed grounds, surrounded by a sea of dynamic burnt orange. Envision the monumental moments embedded in the stadium's history, from the soaring stands to the lively field. With each stride, immerse yourself in the storied tradition and unwavering passion that epitomize the essence of Texas football. Embark on this thrilling journey alongside fellow enthusiasts, where the atmosphere resonates with triumphant echoes and the vibrant legacy of Longhorns pride.",
        image: "https://lh3.googleusercontent.com/pw/ABLVV86afAc0xzk3jddhkf0tJ_1cD7XdW9rn82Pnm4j8nkEZVatlZhCSwhyRTVU23eg34a1Smw9evcx_xyIP5skLXZb7IN2FJLgK6ix4Qu2VOsEYT53q8YeyWIP6YLIrZJXNqNa06bK8zU2bNTZ8eP9KqTpKwTGUFuC-j8_JqvFwz8lr_trak_jWCN89DFWvT3XsyegZvjsBiEueD4sAI1tjYPRV7giLZsIUe9N1mma2ea6Pg_VLBQAlmLRPhLzabB3Ri2t-r6xroNeg6cLfcPYQMTs-XrV-3epKKZloCrrGKtAKNlLyFdnkXQDVI3B9GwJHUL7A6YwgmzXYQyvdVUFc4xMOKYp8uJPVj8ZeyIlNe2YT8tag9nnI84Lq2wbzFIrkujU0YSRkiJzkcdPVgTRlo9o5slpkaloU3kFficntlckBrpJ3VCixBIOiDTWWxqEsghss-7qImQ-LDjYyfFxA62XVQIHs0DDdfbJIQzwZ-J9rw4kLTstCojrzNkLQSi5mER6x0IJnHtQQHA3EZ0ZOSTOXkm2Vn7X2Y5bo-QdjJiTeDmBqSEEfYjrsSf06KSCTtiA7K9AsfSdPFtgJ8PlztVyfyCF6bUEv6pgWcE6n_UMJLKaeuw0diVit9h82H0fXOEvdzhksXA8WVONo0JDZMA61qQR2deMqNtLMXxReXhtw3ayEXTE1t0r2TAZYWcRuJsvmHrPq-izEeNZ-A2NP_tZaH_7Eugygw6zP41bQZ9AAEnmo6lvlf9H5cwHI3-mKBuDkW_1gRmYFhQxfPmLi_h9OXP20i0WMeBNqKHvEm20QmBmhHzlkVmzTaTYmhjq0QWNwX6UkrCtC28QvDB8ahzvnh1cVv7ujtT_jowMVGHbaI2TkJsfBh4J4oLCFjUXU5Q=w1024-h576-s-no?authuser=0",
        price: 25
    },
    {
        id: 15,
        name: "Kyle Field",
        team: "Texas A&M Aggies",
        info: "Experience the pulsating energy of Kyle Field like never before! This tour is a magnetic journey through the heart of Aggie pride. Picture yourself amidst a sea of maroon-clad fans, the air alive with the electric spirit of Texas A&M football. As you traverse this legendary stadium, feel the historic resonance of every cheer and monumental play. From the colossal stands to the vibrant field, Kyle Field stands tall as a living testament to the rich legacy of Aggie tradition. Join the symphony of devoted supporters and dive into the scintillating fervor that defines the very essence of college football in College Station.",
        image: "https://lh3.googleusercontent.com/pw/ABLVV87tfoUnK5wt6K7YVAL3ckn53KKrpev38WpLF-CgA0sZFzt5lQ2ofnBhN9naF0X1vtFLcbTujlasd8y0iIilxx0qUBrlFRKSrgzIodrEdislp3OmQHa9J1CLnV6ZezIDRyHJY9LKNpcG-d-la9eUgl1kPIiJ0HQ2wYQG-ESAGtoREQg1ZUmWEFrye_CJ0M1WfLWfpMFO7VCeQL-JibXmiLYSZH14Qo9VMmHwqgmmHmiDs_bziPZITZfvn-tV4wZabRaim2D3D1qNHx86xMH7_fDk7UJJo2m4HXlRvZM97j1LVg6NoIPK8MPqcAjuhUdQukLMgJ7YAW208DDIcRsA1sWVSYDifj8o5t2c5YxA5GenK0e7hLADwc4DK39_i8Ct9yTT4hhAtdJAhfzZ2vzT6mbOtxGTjiFgyTzE2zjdvgHuZM4s_am3QqKMKn_8cjdjTAYxfSA7hbocaO_8U3fRRHTw56jnGHcfyhBDJZEy9Z8zCDd_SWQ9n5QHHcsx_gClfAhlZI0Fuf_ml7Wmj8qYYXBAX5-f-GhzwzWndYTLjtzqDjdPDups7CiZ9aDH5bEtOhOOuztHVF9l0jiqYW5maYjEUmkn54d3i7gC96eQABnBDul5j-cJqlszNzUuL0jaFV13P3ctxXO7dy-O3kDuLUxPwVsqYWs8Y7_CZY--_Bu1Qkhlwdq1JkdV6FnmYDzL4QjAcvI138Z9I3ftyA0khBVs862Ig7Wq52nTtmuEXq3Vy_wuc6M160p0Gvlf9-MUrOqxIDjK_EPWmc_Pk7rkJYX0sn0jN9dWd3VABw07S-2eD-x2Qb0844DDu78OhhdoPAksTYdCbYVUUIXTZsb8RL7VYCGklxQxLVYX0dTf9Vclsp1t7a2RRrJpWsGAZYXnsg=w1024-h576-s-no?authuser=0",
        price: 25
    },
    {
        id: 16,
        name: "Dudley Field",
        team: "Vanderbilt Commodores",
        info: "Get set for an exciting journey into the heart of the action at Vanderbilt's Dudley Field! This tour is your exclusive pass to the dynamic rhythm of Commodore pride. Envision yourself amidst a sea of enthusiastic fans, the atmosphere alive with the spirited energy of Vanderbilt football. While navigating this lively stadium, immerse yourself in the historic echoes of triumphant cheers and unforgettable plays. From the spirited stands to the animated field, Dudley Field stands as a vibrant tribute to the rich legacy of Commodore tradition. Join the chorus of passionate fans and relish in the lively vibes that make each visit to this stadium a joyful celebration of Vanderbilt spirit.",
        image: "https://lh3.googleusercontent.com/pw/ABLVV85QenmWaOpKwZk4oXOqqMmZR-uJJ2q49FeliSdByUobbNP5z8ADZmS0vr0TD0s8Ij8bh8nmqf8ggzJ0w35RUxjv9K-eMhIQA598scNVDRxzkqRXv7kJBir_VSXQOihTULbMVoBVEAxECyyQxBbVLayg7mkysaoOmrX645Vbvxf-ha4Yrxn9tu-TdV42UPo8VDdJugb6YBbCLLzS1ax3iJHV_r_NYqPi57OIfSlwLDoInfZ8D9150McAb897Qs828ZOPOYYEWpg8yzEmPdXpSj45WBQ_zEgaqZ0ffDCUIl_JajJ_H9pxl57lFB3ulF0R96f7cKx1GY7GCSW-HBk08CfQ0baUgaEOq-ubwBqVDX6uRVtnTRszTxuwAbyvBwUNGyBKmy_ZxXVoxL36Bdtqv-GWiQkhnvTulSFOUukcw5rHeXyqARF2vcL5wA0rINi9ykTdYHl0xg1arEfWdmUq-4himdz_lKt0i7g7xxMC_SmDAl19tOUEAwb-AvW4D5myFAI2RS4fADmgV68uIAO2dfRAnGYolYcP0W4d7W-GA4jWBcUKzP4TcmTiWrQbpjOmE4yCYRsmuVNB2HpKdrH0KlavjRCTwaMYE5o4f1QmkSsBVjSvDys5gHuGWI-vZEhnOH9P-DJhvBazGfB-LfjHEMH-9GfOAF-ZOUN1hjG9Ge8Y5wDdw7vWH8gmqJzntO_q_xTHI9-Dhb2Yti_wAuI12q2n1AnHlF0_xfdpLOB4FNWSyVh_OokClWrZ9DsbDn1aaiw6QCWvcUcGQ4u-n2RWH9NbXdtSOpKhUkqe0w50EhFtMGQF4gr0-AgKVR11MZ7-tsEYekzAHVC-PH0nV0BdS2OOx0au3fq0JMxM6nvwWjlsaRXgRwEoqeVhyTBp2ypqLA=w1024-h576-s-no?authuser=0",
        price: 20
    },
];

app.get('/api/stadiums', (req, res) => {
    res.json(stadiums);
});

app.listen(port, () => {
    console.log(`Server is running on port ${port}`);
});